//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenschicht
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQRCode
    {
        public string QRBAN { get; set; }
        public double Ovocoin { get; set; }
        public bool Eingeloggt { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
