//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenschicht
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBegriff
    {
        public int IDBegriff { get; set; }
        public string Begriff { get; set; }
        public int FKKategorie { get; set; }
    
        public virtual tblkategorie tblkategorie { get; set; }
    }
}
