//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenschicht
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbCasino_IN19Entities : DbContext
    {
        public dbCasino_IN19Entities()
            : base("name=dbCasino_IN19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBegriff> tblBegriff { get; set; }
        public virtual DbSet<tblHighscore> tblHighscore { get; set; }
        public virtual DbSet<tblkategorie> tblkategorie { get; set; }
        public virtual DbSet<tblQRCode> tblQRCode { get; set; }
        public virtual DbSet<tblSpiel> tblSpiel { get; set; }
    
        [DbFunction("dbCasino_IN19Entities", "fTop100")]
        public virtual IQueryable<fTop100_Result> fTop100(string refSpiel)
        {
            var refSpielParameter = refSpiel != null ?
                new ObjectParameter("refSpiel", refSpiel) :
                new ObjectParameter("refSpiel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTop100_Result>("[dbCasino_IN19Entities].[fTop100](@refSpiel)", refSpielParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> pTop100Wert(string refSpiel)
        {
            var refSpielParameter = refSpiel != null ?
                new ObjectParameter("refSpiel", refSpiel) :
                new ObjectParameter("refSpiel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("pTop100Wert", refSpielParameter);
        }
    
        [DbFunction("dbCasino_IN19Entities", "fTop100Neu")]
        public virtual IQueryable<fTop100Neu_Result> fTop100Neu(Nullable<int> refSpiel)
        {
            var refSpielParameter = refSpiel.HasValue ?
                new ObjectParameter("refSpiel", refSpiel) :
                new ObjectParameter("refSpiel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTop100Neu_Result>("[dbCasino_IN19Entities].[fTop100Neu](@refSpiel)", refSpielParameter);
        }
    
        public virtual int pTop100WertNeu(Nullable<int> refSpiel, ObjectParameter score)
        {
            var refSpielParameter = refSpiel.HasValue ?
                new ObjectParameter("refSpiel", refSpiel) :
                new ObjectParameter("refSpiel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pTop100WertNeu", refSpielParameter, score);
        }
    }
}
