//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQRCode
    {
        public string QRBAN { get; set; }
        public double Ovocoin { get; set; }
        public bool Eingeloggt { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
