//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q4R
    {
        public int IDQR { get; set; }
        public string QRBAN { get; set; }
        public double value { get; set; }
        public bool istAktiv { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
