//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datenschicht
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHighscore
    {
        public int IDHighscore { get; set; }
        public Nullable<int> FKSpiel { get; set; }
        public string Spieler { get; set; }
        public double Punkte { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual tblSpiel tblSpiel { get; set; }
    }
}
